### ISSUE TITLE
Unable to figure out the syntax to import a model from a different app now that ModelForms are in play

### ISSUE THREAD

**Issue by dgets** [dgets/lasttime#15]
Running into the same problem that I originally had from #5 again, now that I've switched from using models & forms separately in `subadd` to utilizing `ModelForms` to avoid redundancy.  This is in trying to find the proper solution to #11, which I just closed, as everything seems to be working, except for accessing the query of the `Substance` records.

**Comment by dgets** [comment]
See also: https://github.com/dgets/lasttime/blob/682db29864fdee847556c004ba00c84022da2412/recadm/forms.py#L5

...which I have replaced with `sub = forms.ModelChoiceField(queryset=subadd.Substance)`, along with at least a dozen other variations (including variations of `from` imports).

**Comment by georgedorn** [comment]
Try:

```
from subadd.models import Substance
[...]
sub = forms.ModelChoiceField(queryset=Substance.objects.all())
```

Later, you may want to change that queryset dynamically, for instance to filter by the currently-logged-in user.  A pretty solid example of doing this is here:

https://stackoverflow.com/questions/51512606/django-forms-queryset

**Comment by dgets** [comment]
How exceedingly odd, I could swear that I tried exactly that.  I bet I tried every combination of things like it, but never matched up those 2 lines properly.  m(

Thank you for your input, sir.  It is much appreciated.
